export const LOAD_CAMPAIGNS_FETCHING = 'LOAD_CAMPAIGNS_FETCHING';
export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS';
export const LOAD_CAMPAIGNS_ERROR = 'LOAD_CAMPAIGNS_ERROR';

export const LOAD_CAMPAIGN_BY_ID_FETCHING = 'LOAD_CAMPAIGN_BY_ID_FETCHING';
export const LOAD_CAMPAIGN_BY_ID_SUCCESS = 'LOAD_CAMPAIGN_BY_ID_SUCCESS';
export const LOAD_CAMPAIGN_BY_ID_ERROR = 'LOAD_CAMPAIGN_BY_ID_ERROR';

export const INIT_STATES = 'INIT_STATES';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';


